POST http://localhost:5000/ValidaRegra
content-type: application/json

{
 "ORIGEM" : 0,
 "MACA" : 10,
 "BATATINHA" : 3,
 "BANANA": 26,
 "Feira": 1,
 "regra" : "ORIGEM == 1 && (MACA == 10 && (BATATINHA == 3 || BATATINHA == 4 || BATATINHA == 6 || BATATINHA == 9 || BATATINHA == 7 || BATATINHA == 8 || BATATINHA == 10 || BATATINHA == 18 || BATATINHA == 20 || BATATINHA == 235 || BATATINHA == 26 || BATATINHA == 27 || BATATINHA == 35 || BATATINHA == 34 || BATATINHA == 33 || BATATINHA == 36 || BATATINHA == 37 || BATATINHA == 38) && BANANA == 26) || (MACA == 60 && (BATATINHA == 3 || BATATINHA == 6 || BATATINHA == 7 || BATATINHA == 260) && BANANA == 26) || MACA == 19 && ((BATATINHA == 3 || BATATINHA == 4 || BATATINHA == 20 || BATATINHA == 34) && BANANA == 26) || ((BATATINHA == 6 || BATATINHA == 7 || BATATINHA == 8) && BANANA == 3) || ((BATATINHA == 33) && BANANA == 40) || MACA == 14 && (BATATINHA == 3 && BANANA == 40) || (BATATINHA == 6 && BANANA == 3) && Feira == 1"
 }

###

POST http://localhost:5000/ValidaRegra
content-type: application/json

{
 "ORIGEM" : 0,
 "FLOR" : "ESPINHO",
 "ROSA": "x",
 "CRAVO" : 7,
 "BROMELIA" : 0,
 "CHAVE" : 0,
 "Choveu" : 1,
 "MARGARIDA" : 3,
 "GIRASSOL": 1,
 "ORQUIDEA": 3,
 "AZALEIA" : -1,
 "LIRIO" : 0,
 "regra" : "ORIGEM == 1 || (FLOR == '' || ROSA == '' || FLOR == 'ESPINHO' || CRAVO == 1) && CRAVO != 2 && CRAVO != 3 && CRAVO != 4 && CRAVO != 5 && CRAVO != 6 || BROMELIA != 1 && BROMELIA != 2 && BROMELIA != 3 && BROMELIA != 4 && BROMELIA != 5 && BROMELIA != 6 && BROMELIA != 7 && BROMELIA != 11 && (CHAVE != 1 || Choveu == 0) && (ORIGEM == 0 || CRAVO != 7 || MARGARIDA != 1 && MARGARIDA != 2 || BROMELIA != 8) && ((BROMELIA == 12 || BROMELIA == 13 || BROMELIA == 14 || BROMELIA == 15 || BROMELIA == 16 || BROMELIA == 17 || BROMELIA == 18 || BROMELIA == 19 || BROMELIA == 20 || BROMELIA == 21 || BROMELIA == 22 || CRAVO == 23 || CRAVO == 38 || BROMELIA == 50 || BROMELIA == 51) || GIRASSOL < ORQUIDEA && (AZALEIA < 0) && LIRIO == 0)"
}